# Generated by Django 3.2.23 on 2024-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0003_auto_20240102_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='location_description',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='shelf',
            name='x_coordinate',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='shelf',
            name='y_coordinate',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='shelf',
            name='z_coordinate',
            field=models.IntegerField(default=-1),
        ),
    ]
